name: AOT Compilation and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: macos-latest
            runtime: osx-x64
          - os: ubuntu-latest
            runs-on: ubuntu-20.04-arm64
            runtime: linux-arm64
          - os: windows-latest
            runtime: win-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build with AOT
      run: |
        dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained -o out/${{ matrix.runtime }} -p:UseAppHost=true
      timeout-minutes: 10 
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        CXXFLAGS: "-fuse-ld=lld"
        LDFLAGS: "-fuse-ld=lld"
        
    - name: Zip the build output
      run: |
        cd out/${{ matrix.runtime }}
        zip -r ../${{ matrix.runtime }}.zip .
        ls
      timeout-minutes: 5
      shell: bash
      
    - name: Upload
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        files: out/*
