name: AOT Compilation and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: macos-latest
            runtime: osx-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build with AOT
      run: |
        dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained -o out/${{ matrix.runtime }} -p:UseAppHost=true
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Zip the build output
      run: |
        cd out/${{ matrix.runtime }}
        zip -r ../${{ matrix.runtime }}.zip .
        ls
      shell: bash
      
    - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: out/*
